// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Host struct {
	ID        int64          `json:"id"`
	Ip        string         `json:"ip"`
	Port      int64          `json:"port"`
	Isp       sql.NullString `json:"isp"`
	Asn       sql.NullString `json:"asn"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	CreatedAt time.Time      `json:"created_at"`
	Active    bool           `json:"active"`
	ScannedAt sql.NullTime   `json:"scanned_at"`
}

type Model struct {
	ID        int64     `json:"id"`
	HostID    int64     `json:"host_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
