// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Host struct {
	ID              int64          `json:"id"`
	Ip              string         `json:"ip"`
	Port            int64          `json:"port"`
	Isp             sql.NullString `json:"isp"`
	Asn             sql.NullString `json:"asn"`
	Country         sql.NullString `json:"country"`
	City            sql.NullString `json:"city"`
	CreatedAt       time.Time      `json:"created_at"`
	Active          bool           `json:"active"`
	ScannedAt       sql.NullTime   `json:"scanned_at"`
	ScanCount       int64          `json:"scan_count"`
	FailedScanCount int64          `json:"failed_scan_count"`
	SslEnabled      bool           `json:"ssl_enabled"`
}

type Inference struct {
	ID               int64          `json:"id"`
	ModelID          int64          `json:"model_id"`
	Prompt           string         `json:"prompt"`
	Response         sql.NullString `json:"response"`
	TotalDurationMs  sql.NullInt64  `json:"total_duration_ms"`
	PromptTokens     sql.NullInt64  `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64  `json:"completion_tokens"`
	Verdict          sql.NullString `json:"verdict"`
	CreatedAt        time.Time      `json:"created_at"`
	HttpStatusCode   sql.NullInt64  `json:"http_status_code"`
	Notes            sql.NullString `json:"notes"`
}

type Model struct {
	ID            int64          `json:"id"`
	HostID        int64          `json:"host_id"`
	Name          string         `json:"name"`
	Size          sql.NullInt64  `json:"size"`
	Family        sql.NullString `json:"family"`
	ParameterSize sql.NullString `json:"parameter_size"`
	Digest        sql.NullString `json:"digest"`
	CreatedAt     time.Time      `json:"created_at"`
}
