// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteModelsByHost = `-- name: DeleteModelsByHost :exec
DELETE FROM models 
WHERE host_id = (SELECT id FROM hosts WHERE ip = ?)
`

func (q *Queries) DeleteModelsByHost(ctx context.Context, ip string) error {
	_, err := q.db.ExecContext(ctx, deleteModelsByHost, ip)
	return err
}

const getIPs = `-- name: GetIPs :many
SELECT ip, port FROM hosts where active = 1
`

type GetIPsRow struct {
	Ip   string `json:"ip"`
	Port int64  `json:"port"`
}

func (q *Queries) GetIPs(ctx context.Context) ([]GetIPsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIPsRow
	for rows.Next() {
		var i GetIPsRow
		if err := rows.Scan(&i.Ip, &i.Port); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomModelByIP = `-- name: GetRandomModelByIP :one
SELECT 
    m.id, 
    m.name, 
    h.ip, 
    h.port
FROM models m
JOIN hosts h ON m.host_id = h.id
WHERE h.ip = ?
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomModelByIPRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Ip   string `json:"ip"`
	Port int64  `json:"port"`
}

func (q *Queries) GetRandomModelByIP(ctx context.Context, ip string) (GetRandomModelByIPRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomModelByIP, ip)
	var i GetRandomModelByIPRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.Port,
	)
	return i, err
}

const getUncensoredModels = `-- name: GetUncensoredModels :many
SELECT name, size, family, parameter_size, digest, created_at 
FROM models 
WHERE name LIKE '%uncensored%'
`

type GetUncensoredModelsRow struct {
	Name          string         `json:"name"`
	Size          sql.NullInt64  `json:"size"`
	Family        sql.NullString `json:"family"`
	ParameterSize sql.NullString `json:"parameter_size"`
	Digest        sql.NullString `json:"digest"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) GetUncensoredModels(ctx context.Context) ([]GetUncensoredModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUncensoredModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUncensoredModelsRow
	for rows.Next() {
		var i GetUncensoredModelsRow
		if err := rows.Scan(
			&i.Name,
			&i.Size,
			&i.Family,
			&i.ParameterSize,
			&i.Digest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHost = `-- name: InsertHost :exec
INSERT INTO hosts (ip, port, isp, asn, country, city, scanned_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertHostParams struct {
	Ip        string         `json:"ip"`
	Port      int64          `json:"port"`
	Isp       sql.NullString `json:"isp"`
	Asn       sql.NullString `json:"asn"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	ScannedAt sql.NullTime   `json:"scanned_at"`
}

func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) error {
	_, err := q.db.ExecContext(ctx, insertHost,
		arg.Ip,
		arg.Port,
		arg.Isp,
		arg.Asn,
		arg.Country,
		arg.City,
		arg.ScannedAt,
	)
	return err
}

const insertModel = `-- name: InsertModel :exec
INSERT INTO models (host_id, name)
VALUES (?, ?)
`

type InsertModelParams struct {
	HostID int64  `json:"host_id"`
	Name   string `json:"name"`
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) error {
	_, err := q.db.ExecContext(ctx, insertModel, arg.HostID, arg.Name)
	return err
}

const listHosts = `-- name: ListHosts :many

SELECT id, ip, port, isp, asn, country, city, created_at, active, scanned_at FROM hosts
`

// db/queries.sql
func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Port,
			&i.Isp,
			&i.Asn,
			&i.Country,
			&i.City,
			&i.CreatedAt,
			&i.Active,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByHost = `-- name: ListModelsByHost :many
SELECT id, host_id, name, created_at FROM models
WHERE host_id = ?
ORDER BY created_at DESC
`

type ListModelsByHostRow struct {
	ID        int64     `json:"id"`
	HostID    int64     `json:"host_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListModelsByHost(ctx context.Context, hostID int64) ([]ListModelsByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsByHostRow
	for rows.Next() {
		var i ListModelsByHostRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveInference = `-- name: SaveInference :exec
INSERT INTO inferences (
    model_id, 
    prompt, 
    response, 
    total_duration_ms, 
    prompt_tokens, 
    completion_tokens,
    verdict,
    http_status_code,
    notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type SaveInferenceParams struct {
	ModelID          int64          `json:"model_id"`
	Prompt           string         `json:"prompt"`
	Response         sql.NullString `json:"response"`
	TotalDurationMs  sql.NullInt64  `json:"total_duration_ms"`
	PromptTokens     sql.NullInt64  `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64  `json:"completion_tokens"`
	Verdict          sql.NullString `json:"verdict"`
	HttpStatusCode   sql.NullInt64  `json:"http_status_code"`
	Notes            sql.NullString `json:"notes"`
}

func (q *Queries) SaveInference(ctx context.Context, arg SaveInferenceParams) error {
	_, err := q.db.ExecContext(ctx, saveInference,
		arg.ModelID,
		arg.Prompt,
		arg.Response,
		arg.TotalDurationMs,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Verdict,
		arg.HttpStatusCode,
		arg.Notes,
	)
	return err
}

const saveModel = `-- name: SaveModel :exec
INSERT INTO models (
    host_id, 
    name, 
    size, 
    family, 
    parameter_size, 
    digest
) VALUES (
    (SELECT id FROM hosts WHERE ip = ? LIMIT 1), 
    ?, ?, ?, ?, ?
)
`

type SaveModelParams struct {
	Ip            string         `json:"ip"`
	Name          string         `json:"name"`
	Size          sql.NullInt64  `json:"size"`
	Family        sql.NullString `json:"family"`
	ParameterSize sql.NullString `json:"parameter_size"`
	Digest        sql.NullString `json:"digest"`
}

func (q *Queries) SaveModel(ctx context.Context, arg SaveModelParams) error {
	_, err := q.db.ExecContext(ctx, saveModel,
		arg.Ip,
		arg.Name,
		arg.Size,
		arg.Family,
		arg.ParameterSize,
		arg.Digest,
	)
	return err
}

const updateHostActive = `-- name: UpdateHostActive :exec
UPDATE hosts SET active = 1, scanned_at=CURRENT_TIMESTAMP WHERE ip = ?
`

func (q *Queries) UpdateHostActive(ctx context.Context, ip string) error {
	_, err := q.db.ExecContext(ctx, updateHostActive, ip)
	return err
}

const updateHostInactive = `-- name: UpdateHostInactive :exec
UPDATE hosts SET active = 0, scanned_at=CURRENT_TIMESTAMP WHERE ip = ?
`

func (q *Queries) UpdateHostInactive(ctx context.Context, ip string) error {
	_, err := q.db.ExecContext(ctx, updateHostInactive, ip)
	return err
}
