// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const insertHost = `-- name: InsertHost :exec
INSERT INTO hosts (ip, port, isp, asn, country, city, scanned_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertHostParams struct {
	Ip        string         `json:"ip"`
	Port      int64          `json:"port"`
	Isp       sql.NullString `json:"isp"`
	Asn       sql.NullString `json:"asn"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	ScannedAt sql.NullTime   `json:"scanned_at"`
}

func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) error {
	_, err := q.db.ExecContext(ctx, insertHost,
		arg.Ip,
		arg.Port,
		arg.Isp,
		arg.Asn,
		arg.Country,
		arg.City,
		arg.ScannedAt,
	)
	return err
}

const listHosts = `-- name: ListHosts :many

SELECT id, ip, port, isp, asn, country, city, created_at, active, scanned_at FROM hosts
`

// db/queries.sql
func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Port,
			&i.Isp,
			&i.Asn,
			&i.Country,
			&i.City,
			&i.CreatedAt,
			&i.Active,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
